[2024-06-04T23:35:36.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-04T23:35:36.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_data.conectando_con_redshift manual__2024-06-04T23:35:29.225305+00:00 [queued]>
[2024-06-04T23:35:36.215+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_data.conectando_con_redshift manual__2024-06-04T23:35:29.225305+00:00 [queued]>
[2024-06-04T23:35:36.216+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-04T23:35:36.225+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): conectando_con_redshift> on 2024-06-04 23:35:29.225305+00:00
[2024-06-04T23:35:36.232+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-04T23:35:36.234+0000] {standard_task_runner.py:63} INFO - Started process 81 to run task
[2024-06-04T23:35:36.234+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_data', 'conectando_con_redshift', 'manual__2024-06-04T23:35:29.225305+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/entregable_dag.py', '--cfg-path', '/tmp/tmpx713fmxw']
[2024-06-04T23:35:36.235+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask conectando_con_redshift
[2024-06-04T23:35:36.276+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_data.conectando_con_redshift manual__2024-06-04T23:35:29.225305+00:00 [running]> on host fd0d5636e48d
[2024-06-04T23:35:36.341+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Guillermo Hern√°ndez' AIRFLOW_CTX_DAG_ID='ingestion_data' AIRFLOW_CTX_TASK_ID='conectando_con_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-06-04T23:35:29.225305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-04T23:35:29.225305+00:00'
[2024-06-04T23:35:36.342+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-04T23:35:38.389+0000] {logging_mixin.py:188} INFO - Connection successfully!
[2024-06-04T23:35:39.011+0000] {python.py:237} INFO - Done. Returned value was: <connection object at 0x7fcb46e76340; dsn: 'user=hernandez17_guillermo_coderhouse password=xxx dbname=data-engineer-database host=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com port=5439', closed: 0>
[2024-06-04T23:35:39.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-04T23:35:39.027+0000] {xcom.py:675} ERROR - Object of type connection is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-06-04T23:35:39.029+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'psycopg2.extensions.connection'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type connection is not JSON serializable
[2024-06-04T23:35:39.040+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_data, task_id=conectando_con_redshift, run_id=manual__2024-06-04T23:35:29.225305+00:00, execution_date=20240604T233529, start_date=20240604T233536, end_date=20240604T233539
[2024-06-04T23:35:39.061+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task conectando_con_redshift (Object of type connection is not JSON serializable; 81)
[2024-06-04T23:35:39.103+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-04T23:35:39.138+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-04T23:35:39.139+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
